=== Roll20/roll20-api-scripts/Voice Menu Manager/tests/roll20-script.schema.json
{
  "$id": "roll20.net/scripts/script.json.schema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Roll20 API Script JSON Schema",
  "description": "Schema to validate script.json for roll20 scripts",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the API script as it will appear on Roll20",
      "type": "string"
    },
    "script": {
      "description": "The name of the javascript file, which must remain uniform throughout versions",
      "type": "string",
      "pattern": "^.*\\.js$"
    },
    "version": {
      "description": "The current version number of the API script (e.g. 12.3)",
      "type": "string",
      "pattern": "^([0-9]+(\\.)?)+([0-9]+)?$"
    },
    "previousversions": {
      "description": "All previous versions of the script in an array format (e.g. [\"0.5\",\"0.1\"])",
      "type": "array",
      "items": {
        "type": ["string", "integer", "number"],
        "pattern": "^([0-9]+(\\.)?)+([0-9]+)?$"
      },
      "uniqueItems": true
    },
    "description": {
      "description": "A short explanation of the script and it's use that will appear along side the script on Roll20. It is important for this section to be filled out in detail, as it's the primary way users will get information about the purpose and use of the script. Included in the description section needs to be an example use or purpose, list and explanation of API Commands, and any other information necessary to operating the script.",
      "type": "string"
    },
    "authors": {
      "description": "A simple string telling who contributed toward the script (e.g. Riley Dutton,Steve Koontz)",
      "type": ["array", "string"],
      "items": {
        "type": "string"
      }
    },
    "roll20userid": {
      "description": "A simple string telling the Roll20 User ID's of the authors (e.g. 1 or 45672,145678). Used internally and won't be shown publicly on the site.",
      "type": ["string", "integer", "array"],
      "pattern": "^([0-9]+,[ ]?)*[0-9]+$",
      "items": {
        "type": ["string", "integer"],
        "pattern": "^[0-9]+$"
      }
    },
    "patreon": {
      "description": "Place the URL for a Patreon campaign here, and it will appear under your script's description when selected via one-click. (e.g. \"https://www.patreon.com/<name>\")",
      "type": "string",
      "pattern": "^(http(s)?://(www\\.)?patreon.com/.*)?"
    },
    "tipeee":{
      "description": "Place the URL for a Tipeee here, and it will appear under your script's description when selected via one-click. (e.g. \"https://www.tipeee.com/<name>\")",
      "type": "string",
      "pattern": "^(http(s)?://(www\\.)?tipeee.com/.*)?"
    },
    "useroptions": {
      "description": "An array of hashes that allow script authors to set pre-determined options for users to customize the functionality of the script. For more information check out the _Example folder's script.json for an example or see the Roll20 Wiki for more documentation.",
      "type": ["array", "object"],
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type":{
            "type": "string",
            "enum": ["text", "number", "select", "checkbox"]
          },
          "default": {
            "type": ["string", "number"]
          },
          "description": {
            "type": "string"
          }
        },
        "required": ["name", "description", "type"]
      },
      "maxProperties": 0
    },
    "dependencies": {
      "description": "A list of other API scripts this script requires to function (e.g. My Kitchen)",
      "type": ["array", "object"],
      "items": {
        "type": "string"
      },
      "additionalProperties": false,
      "properties": {}
    },
    "modifies": {
      "description": "A list of the common Roll20 objects and properties the script reads and writes to. Custom objects and properties inside a namespace don't need to be included. (e.g. bar1_value: write)",
      "type": ["array", "object"],
      "maxItems": 0,
      "additionalProperties": {
        "type": "string",
        "enum": ["read", "write", "read, write", "write, read", "read,write", "write,read"]
      }
    },
    "conflicts":{
      "description": "A list of other API scripts this script is known to conflict with (e.g. Recipes)",
      "type": ["array", "object"],
      "items": {
        "type": "string"
      },
      "maxProperties": 0
    }
  },
  "required": ["name", "description", "script", "version", "authors", "roll20userid"]
}

=== Roll20/roll20-api-scripts/CypherSystemSheet/script.json
{
  "name": "Cypher System Sheet",
  "script": "cyphersystemsheet.js",
  "previousversions" : [],
  "version": "1.2",
  "description": "Enables the applying of stat cost, recovery roll advance, auto calculation of PC state and damage track in the Cypher System Sheet, from the roll template, sheet buttons and/or macros. Read the [Wiki page](https://wiki.roll20.net/Script:Cypher_System_Sheet) for help about chat commands and macros.",
  "authors": "Natha",
  "roll20userid": "75857",
  "useroptions": [],
  "dependencies": {},
  "modifies": {
    "token": "write",
    "bar1_value": "write",
    "bar2_value": "write",
    "bar3_value": "write",
    "character": "write"
  },
  "conflicts": ["Natha's Numenera"]
}

=== Roll20/roll20-api-scripts/InitiativeAssistant/script.json
{
  "name": "InitiativeAssistant",
  "version": "0.1.6",
  "description": "Provides an easy interface to adding players to the inititaive order.\r\rFor instructions, run `!init-assist --help`, or visit [InitiativeAssistant Forum Thread](https://app.roll20.net/forum/permalink/1854729/).",
  "authors": "The Aaron",
  "roll20userid": "104025",
  "patreon": "https://www.patreon.com/shdwjk",
  "dependencies": {},
  "modifies": {
    "state.InitiativeAssistant": "read,write",
    "campaign.turnorder": "read,write",
    "character.name": "read",
    "token.represents": "read"
  },
  "conflicts": [],
  "script": "InitiativeAssistant.js",
  "useroptions": [],
  "previousversions": [
    "0.1.3",
    "0.1.4",
    "0.1.5"
  ]
}

=== Roll20/roll20-api-scripts/APIHeartBeat/script.json
{
  "name": "APIHeartBeat",
  "version": "0.4.2",
  "description": "Provides an API Heartbeat by setting the requesting player's color continuously.",
  "authors": "The Aaron",
  "roll20userid": "104025",
  "patreon": "https://www.patreon.com/shdwjk",
  "dependencies": [],
  "modifies": {
    "state.APIHeartBeat": "read,write",
    "player.color": "write",
    "player.id": "read"
  },
  "conflicts": [],
  "script": "APIHeartBeat.js",
  "useroptions": [],
  "previousversions": [
    "0.4.1"
  ]
}

=== Roll20/roll20-api-scripts/OneWayDynamicLighting/script.json
{
    "name": "One-Way Dynamic Lighting",
    "script": "script.js",
    "version": "1.0.2",
    "previousversions": [],
    "description": "# One-Way Dynamic Lighting\r\rThis script allows you to set up dynamic lighting walls that allow you to\rsee through one side, but not the other.\r\r### Creating Walls\r\rTo create a one-way dynamic lighting wall, you need to create a path for the wall itself and\ra filled path representing a area from which characters can see through the wall. Once you have those\rtwo objects created, select both of them, and activate the ```OneWayDynamicLighting``` macro installed\rby this script. That's all there is to it!\r\r__Note:__\rDue to limitations of the API, if at least one player character is on the visible\rside of the wall, then all characters will be able to see through it, even if\ryour dynamic lighting is set to require line-of-sight. This is because it works by\rmoving the one-way walls back and forth from the GM layer and the Dynamic Lighting layer,\rwhich at any point in time is the same for everyone.\r\rAlas, there are some paradigms I've considered when implementing this script that\rwould allow each character to have their own perspective of the dynamic lighting.\rUnfortunately, this would only be possible if it were implemented in Roll20's\rdynamic lighting system itself using some WebGL magic involving stencil buffers\rand lighting polygon unions.\r\rA while ago, I presented an algorithm for\rimplementing one-way dynamic lighting in the dynamic lighting system detailed in\rmy post here: https://app.roll20.net/forum/post/4804351/questions-roll20-roundtable-hour-number-1-q1-2017/?pageforid=4806305#post-4806305\rIf it's compatible with their current system, maybe the Roll20 developers can make use of it.\rFor the time being though, I hope that this humble script will suffice for everyone's\rone-way dynamic lighting needs.\r\r### Help\r\rIf you experience any issues while using this script,\rneed help using it, or if you have a neat suggestion for a new feature, please\rpost to the script's thread in the API forums or shoot me a PM:\rhttps://app.roll20.net/users/46544/stephen-l\r\r### Show Support\r\rIf you would like to show your appreciation and support for the work I do in writing,\rupdating, and maintaining my API scripts, consider buying one of my art packs from the Roll20 marketplace (https://marketplace.roll20.net/browse/search/?keywords=&sortby=newest&type=all&genre=all&author=Stephen%20Lindberg)\ror, simply leave a thank you note in the script's thread on the Roll20 forums.\rEither is greatly appreciated! Happy gaming!\r",
    "authors": "Stephen Lindberg",
    "roll20userid": 46544,
    "useroptions": [],
    "dependencies": ["Path Math"],
    "modifies": {},
    "conflicts": []
}

=== Roll20/roll20-api-scripts/WorldMapDiscovery/script.json
{
    "name": "World Map Discovery",
    "script": "WorldMapDiscovery.js",
    "version": "1.1",
    "previousversions": ["1.0"],
    "description": "# World Map Discovery\r\r_v1.1 Updates:_\r* Location discoveries now display an HTML-formatted message to the chat.\r* When locations are discovered, their white-tower status is removed.\r* The script now exposes some of its functions through its WorldMapDiscovery object. See the source code for details.\r\rThis script allows the GM to set hidden locations on a world map that can be\rrevealed when a character gets close enough.\r\r### To use:\r\r1. Turn on the landmark's ```white-tower status``` <img src=\"http://game-icons.net/icons/lorc/originals/png/white-tower.png\" width=\"32\" >.\r2. Set the landmark's ```aura 1 radius``` to whatever radius you want players to come within to discover the landmark.\r3. Put the landmark on the ```GM layer```.\r\r### Discovering landmarks:\r\rWhen a character token moves within the aura radius of the landmark, the landmark\rwill appear on the graphics layer and a message will be displayed\rtelling everyone that the character discovered it. When the landmark is\rdiscovered, its aura1 radius is removed.\r",
    "authors": "Stephen Lindberg",
    "roll20userid": 46544,
    "useroptions": [],
    "dependencies": ["Vector Math"],
    "modifies": {
        "aura1_radius": "read, write",
        "chat": "write",
        "lastmove": "write",
        "layer": "read, write",
        "left": "read, write",
        "status_white-tower": "read",
        "token": "read",
        "top": "read, write"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/Bet/script.json
{
  "name": "Bet",
  "version": "0.1.4",
  "description": "",
  "authors": "The Aaron",
  "roll20userid": "104025",
  "patreon": "https://www.patreon.com/shdwjk",
  "dependencies": {},
  "modifies": {
    "state.Bet": "read,write"
  },
  "conflicts": [],
  "script": "Bet.js",
  "useroptions": [],
  "previousversions": [
    "0.1.3"
  ]
}

=== Roll20/roll20-api-scripts/ScriptCards/script.json
{
    "name": "ScriptCards",
    "script": "scriptcards.js",
    "version": "3.0.23",
    "previousversions": ["3.0.20","3.0.19","3.0.16","3.0.14","3.0.12","3.0.01","3.0.0","2.7.35","2.7.31","2.7.27","2.7.25","2.7.10","2.7.8","2.6.6","2.6.2","2.4.9","2.4.3","2.3.9","2.3.5","2.3.4","2.2.9","2.2.4","2.2.0","2.1.19","2.1.11","2.1.7","2.0.2","1.7.7","1.7.6","1.6.4","1.6.2","1.4.10","1.4.0","1.3.9","1.3.1","1.1.19","1.0.9","1.0.0","0.0.15","0.0.11","0.0.5"],
    "description": "**ScriptCards** allows you to create powerful macros utilizing a built-in scripting language to output nicely formatted display cards for PC and NPC actions, spells, abilities, statistics, or almost any other purpose you can come up with.\n\n Please see the Roll20 API Scripts WIKI for detailed documentation, and the Roll20 API Forum Thread for the most recent details and discussion\n\nScriptCards was designed as a spiritual successor to the PowerCards API script, and addresses some of the often requested abilities that the structure of PowerCards precludes, such as true variables, looping and branching, and the ability to make formatting changes based on conditional results. The default output format for ScriptCards is similar to the power blocks from the official D&D 4E products, but the format works well for any system. ScriptCards are output to the chat window with full HTML/CSS formatting. There is no game-system specific requirements for ScriptCards.",
    "authors": "Kurt Jaegers",
    "patreon": "https://www.patreon.com/KurtJaegers",
    "roll20userid": "2365448"
}

=== Roll20/roll20-api-scripts/ItsATrap_theme_5E_Shaped/script.json
{
    "name": "It's a Trap! - D&D 5E Shaped theme",
    "script": "theme.js",
    "version": "3.0.2",
    "previousversions": ["1.0", "1.1", "1.2", "3.0"],
    "description": "# It's A Trap! - 5th Edition (Shapedv2) theme (Deprecated)\r\r_This script is deprecated. Please use the generic D&D 5E trap theme instead._\r",
    "authors": "Stephen Lindberg",
    "roll20userid": 46544,
    "useroptions": [],
    "dependencies": ["It's a Trap!"],
    "modifies": {},
    "conflicts": []
}
